#pragma once

// #define	SPLIT_HAND_PIN_LOW_IS_LEFT

#define SPI_DRIVER SPID1
#define DISPLAY_SPI_DIVISOR 32
#define DISPLAY_SPI_MODE 3

#define SPI_SCK_PIN  A5
#define SPI_MISO_PIN A6
#define SPI_MOSI_PIN A7

#define PMW33XX_CS_PIN C4
#define POINTING_DEVICE_TASK_THROTTLE_MS 10

#define ENCODER_DEFAULT_POS 3
#define ENCODER_RESOLUTIONS { 2, 4, 4 }

#define DISPLAY_POWER_PIN B10
#define DISPLAY_BL_PIN B2
#define DISPLAY_RST_PIN B1
#define DISPLAY_DC_PIN B0
#define DISPLAY_CS_PIN C5

#define WS2812_PIN A8
#define WS2812_PWM_DRIVER PWMD1
#define WS2812_PWM_CHANNEL 1
#define WS2812_PWM_PAL_MODE 1
#define WS2812_PWM_DMA_STREAM STM32_DMA2_STREAM5
#define WS2812_PWM_DMA_CHANNEL 6

#define RGB_MATRIX_DEFAULT_HUE 5
#define RGB_MATRIX_DEFAULT_SAT 5
#define RGB_TOT_IND_L 67
#define RGB_TOT_IND_R 67
#define RGB_KEYS_L_START 0
#define RGB_KEYS_L_END 35
#define RGB_KEYS_R_START 36
#define RGB_KEYS_R_END 71

#define QUANTUM_PAINTER_DISPLAY_TIMEOUT 0

#define USB_VBUS_PIN D2
#define SERIAL_USART_DRIVER SD1
#define SERIAL_USART_TX_PIN A9
#define SERIAL_USART_RX_PIN A10
#define SERIAL_USART_TX_PAL_MODE 7
#define SERIAL_USART_RX_PAL_MODE 7
#define SERIAL_USART_FULL_DUPLEX
// note that F405's USART1 is not pin swap capable
#ifndef SERIAL_USART_SPEED
#    define SERIAL_USART_SPEED 1200000
#endif // SERIAL_USART_SPEED

#define EXTERNAL_FLASH_SPI_SLAVE_SELECT_PIN	B11
#define EXTERNAL_FLASH_SIZE	(16 * 1024 * 1024) // this equals 128megabits
