// Copyright 2022 Chris Trotter (@Chris Trotter)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define MOUSE_EXTENDED_REPORT
#define POINTING_DEVICE_TASK_THROTTLE_MS 40
#define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE
#define ANALOG_JOYSTICK_X_AXIS_PIN B5
#define ANALOG_JOYSTICK_Y_AXIS_PIN B4
#define ANALOG_JOYSTICK_SPEED_REGULATOR 80
#define POINTING_DEVICE_INVERT_X
#define POINTING_DEVICE_INVERT_Y
