#pragma once
// #define QUANTUM_PAINTER_DEBUG
// #define DEBUG_MATRIX_SCAN_RATE

// #define PMW33XX_LIFTOFF_DISTANCE 0xFF
#define ROTATIONAL_TRANSFORM_ANGLE 90
#define POINTING_DEVICE_INVERT_Y

#define INDICATOR_BRIGHTNESS 90
#define INDICATOR_IDLE_BRIGHTNESS 30