POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER 	= pmw3360

QUANTUM_PAINTER_DRIVERS += st7789_spi
QUANTUM_PAINTER_LVGL_INTEGRATION = no
RAW_ENABLE = yes
KEYBOARD_SHARED_EP = yes

# LED settings
RGB_MATRIX_LEDMAPS_ENABLED = yes 	# turn on per-key colours

SERIAL_DRIVER = usart

# FLASH_DRIVER = spi